### ISSUE TITLE
Fresh Install Issue on OctoPrint 1.4.0

### ISSUE THREAD

**Issue by Ice-Drake** [gillg/OctoPrint-LDAP#12]
I was able to install the plugin successfully; however, I can't seem to get it working properly. I tried installing it using two methods.

First, install it via URL using web-based plugin manager. The plugin did show up in the list of plugins; however, it is disabled by default. While I can enable it via GUI, no new menu or control seems to appear afterward. When I reboot the server, the plugin is disabled yet again.

Second, install it via command line. The plugin didn't show up in the list at all if nothing got installed.

I even search for where I can configure the plugin and found no file in plugins folder.

**Comment by battis** [comment]
@Ice-Drake Pretty sure that this doesn't work with OctoPrint 1.4 yet. I've been working on [a fork](https://battis/OctoPrint-LDAP) that has some more documentation on how to install for OctoPrint 1.3 (that I just merged into this repo), but 1.4 compatibility is still in the works (battis/OctoPrint-LDAP#3). ([I'd been planning to buckle down on that shortly](https://github.com/gillg/OctoPrint-LDAP/pull/11#issuecomment-592603020), but I'm a high school teacher who is now teaching remotely... without my lab, 3D printers, Raspberry Pis... _or LDAP server_ for testing)
