### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [gillg/OctoPrint-LDAP#16]
Could you please tag the source? This allows distributions to get the complete source from GitHub and simplifies the tracking of the releases.

Thanks

**Comment by busti** [comment]
Pinging @battis since he seems to be the one actively maintaining this repo.

**Comment by battis** [comment]
Sorry. Yes. There are a couple issues that need attention in the repo as well. I'll try to take a look tomorrow. (My backlog is… a bit much this semester — teaching too many courses.)

**Comment by gillg** [comment]
Sorry for the delay... ! But 2 new tags created.

0.1.0 for the version working until now.
1.0.0 for the new version which seems have breaking change in the internal OctoPrint API.
