### ISSUE TITLE
Install on raspberry pi, fresh octoprint

### ISSUE THREAD

**Issue by sjo00** [gillg/OctoPrint-LDAP#2]
Command used: 
```
wget https://github.com/gillg/OctoPrint-LDAP/archive/master.zip
/home/pi/oprint/bin/pip install ~/master.zip
```

part of error ( cat /home/pi/.octoprint/logs/plugin_pluginmanager_console.log ):

/home/pi/oprint/include/site/python2.7/python-ldap:
    running install
    running build
    running build_py
    file Lib/ldap.py (for module ldap) not found
    file Lib/ldap/controls.py (for module ldap.controls) not found
    file Lib/ldap/extop.py (for module ldap.extop) not found
    file Lib/ldap/ldapobject.py (for module ldap.ldapobject) not found
    file Lib/ldap/schema.py (for module ldap.schema) not found
    creating build
    creating build/lib.linux-armv7l-2.7
    copying Lib/ldapurl.py -> build/lib.linux-armv7l-2.7
    copying Lib/ldif.py -> build/lib.linux-armv7l-2.7
    copying Lib/slapdtest.py -> build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/__init__.py -> build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/async.py -> build/lib.linux-armv7l-2.7/ldap
    creating build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/__init__.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/deref.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/libldap.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/openldap.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/psearch.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/readentry.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/simple.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/sss.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/controls/vlv.py -> build/lib.linux-armv7l-2.7/ldap/controls
    copying Lib/ldap/cidict.py -> build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/dn.py -> build/lib.linux-armv7l-2.7/ldap
    creating build/lib.linux-armv7l-2.7/ldap/extop
    copying Lib/ldap/extop/__init__.py -> build/lib.linux-armv7l-2.7/ldap/extop
    copying Lib/ldap/extop/dds.py -> build/lib.linux-armv7l-2.7/ldap/extop
    copying Lib/ldap/filter.py -> build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/functions.py -> build/lib.linux-armv7l-2.7/ldap
    creating build/lib.linux-armv7l-2.7/ldap/ldapobject
    copying Lib/ldap/ldapobject/__init__.py -> build/lib.linux-armv7l-2.7/ldap/ldapobject
    copying Lib/ldap/ldapobject/simple.py -> build/lib.linux-armv7l-2.7/ldap/ldapobject
    copying Lib/ldap/ldapobject/reconnect.py -> build/lib.linux-armv7l-2.7/ldap/ldapobject
    copying Lib/ldap/logger.py -> build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/modlist.py -> build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/pkginfo.py -> build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/resiter.py -> build/lib.linux-armv7l-2.7/ldap
    copying Lib/ldap/sasl.py -> build/lib.linux-armv7l-2.7/ldap
    creating build/lib.linux-armv7l-2.7/ldap/schema
    copying Lib/ldap/schema/__init__.py -> build/lib.linux-armv7l-2.7/ldap/schema
    copying Lib/ldap/schema/models.py -> build/lib.linux-armv7l-2.7/ldap/schema
    copying Lib/ldap/schema/subentry.py -> build/lib.linux-armv7l-2.7/ldap/schema
    copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-armv7l-2.7/ldap/schema
    copying Lib/ldap/syncrepl.py -> build/lib.linux-armv7l-2.7/ldap
    file Lib/ldap.py (for module ldap) not found
    file Lib/ldap/controls.py (for module ldap.controls) not found
    file Lib/ldap/extop.py (for module ldap.extop) not found
    file Lib/ldap/ldapobject.py (for module ldap.ldapobject) not found
    file Lib/ldap/schema.py (for module ldap.schema) not found
    running egg_info
    writing requirements to Lib/python_ldap.egg-info/requires.txt
    writing Lib/python_ldap.egg-info/PKG-INFO
    writing top-level names to Lib/python_ldap.egg-info/top_level.txt
    writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    file Lib/ldap.py (for module ldap) not found
    file Lib/ldap/controls.py (for module ldap.controls) not found
    file Lib/ldap/extop.py (for module ldap.extop) not found
    file Lib/ldap/ldapobject.py (for module ldap.ldapobject) not found
    file Lib/ldap/schema.py (for module ldap.schema) not found
    reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'Makefile'
    warning: no files found matching 'Modules/LICENSE'
    writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    running build_ext
    building '_ldap' extension
    creating build/temp.linux-armv7l-2.7
    creating build/temp.linux-armv7l-2.7/Modules
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_SASL -DLDAPMODULE_VERSION=2.5.2 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/include -I/usr/include/sasl -I/usr/local/include -I/usr/local/include/sasl -I/usr/include/python2.7 -c Modules/LDAPObject.c -o build/temp.linux-armv7l-2.7/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:8:0:
    Modules/errors.h:7:18: fatal error: lber.h: Datei oder Verzeichnis nicht gefunden
     #include "lber.h"
                      ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/pi/oprint/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Xkl8gE/python-ldap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x2zJdd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/oprint/include/site/python2.7/python-ldap" failed with error code 1 in /tmp/pip-build-Xkl8gE/python-ldap/

**Comment by gillg** [comment]
You should look at https://github.com/gillg/OctoPrint-LDAP/blob/master/requirements.txt
Pyhton-LDAP needs some system requirements. I not found any solution to auto-install them with pip install script... 
If someone has ideas, I take it :)

**Comment by sjo00** [comment]
Thank you

after installing the requirements ([https://github.com/gillg/OctoPrint-LDAP/blob/master/requirements.txt](https://github.com/gillg/OctoPrint-LDAP/blob/master/requirements.txt))
in commandline with:

`sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev`

the pip install has no error.

I used the following path for pip install, because on clear octoprint image pip was not in /bin or path

`/home/pi/oprint/bin/pip install ~/master.zip`

best regards
