### ISSUE TITLE
OctoPrint-LDAP does not load with OctoPrint 1.8.6

### ISSUE THREAD

**Issue by rramador** [gillg/OctoPrint-LDAP#21]
Updates to OctoPrint have changed the interface to the user manager causing OctoPrint to fail in extending "FilebasedUserManager"

See below:

2022-10-18 10:20:20,407 - octoprint.server - ERROR - Error while creating user manager instance from factory auth_ldap
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/__init__.py", line 552, in run
    userManager = factory(components, self._settings)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_auth_ldap/plugin.py", line 16, in ldap_user_factory
    self._user_manager = LDAPUserManager(plugin=self, ldap=LDAPConnection(plugin=self))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_auth_ldap/user_manager.py", line 24, in __init__
    FilebasedUserManager.__init__(self, group_manager=LDAPGroupManager(plugin=plugin, ldap=ldap), **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/access/users.py", line 521, in __init__
    self._load()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_auth_ldap/user_manager.py", line 162, in _load
    permissions = self._to_permissions(*attributes.get("permissions", []))
AttributeError: 'int' object has no attribute 'get'

Happy to help with debug and try a fix if you have a moment to generate a patch.

**Comment by petrmanek** [comment]
I am running into the same problem, OctoPrint v1.8.6 from the latest OctoPi stable image

**Comment by KoB-OG** [comment]
Same problem here...

**Comment by petrmanek** [comment]
@gillg @battis Can we please get any maintainer response? Currently the plugin cannot be used

**Comment by BlackJaecky** [comment]
Hey had the same problem and therefore edit the plugin. I can not guarantee that it is working perfectly but you can try my fork.
https://github.com/BlackJaecky/OctoPrint-LDAP/archive/refs/heads/master.zip

There are three main problems I addressed with the changes:
- Octoprint users and groups have a version since the 1.8.6 release. It is now version 2. So I added 
`version = data.pop("_version", 1)` 
to remove the version info after loading. Similar to the octoprint code.
- find_user function has a new variable fresh, added `fresh=False` to find_user and ignores the rest.
- After every successful bind a random password is generated and stored for the user. This is needed for the signature_key_for_user.

Maybe you need to delete all LDAP users from the users.yaml for the first run. But try it first without removing them.

Greetings and good night!

**Comment by gillg** [comment]
Hello ! Sorry guys I'm very busy but I will take a look on your issues in coming days.
Thanks in advance @BlackJaecky for your first analysis that will save time! :)

**Comment by gillg** [comment]
I reviewed and merged the PR from @BlackJaecky https://github.com/gillg/OctoPrint-LDAP/pull/22.
Thanks a lot for your fix to make this plugin usable :)

Does everyone can confirm it it solves all your issues ?

**Comment by rramador** [comment]
Thanks for the merge and thanks to @BlackJaecky ! I have pulled and tested in my environment. AuthLDAP is working as expected.

**Comment by petrmanek** [comment]
@gillg Thank you for the merge, and apologies for late response. I am currently out of office, away from my OctoPrint device. Will be able to test the fix in mid-December. I would not want to risk cutting off access to it remotely, so I would suggest that you do not wait for my thumbs up. If I find any faults, I will open another issue.

**Comment by aSilentSniper** [comment]
@gillg Same Problem seems to happen with Octoprint 1.8.7

**Comment by gillg** [comment]
Any news here ? Who can confirm if it's working or not ?

**Comment by aSilentSniper** [comment]
I will take a look tomorrow and give you an update.

**Comment by rramador** [comment]
I tried with 1.9.1 and it is working as expected. LDAP connectivity and user groups are being mapped correctly.

**Comment by petrmanek** [comment]
@gillg just tried it with 1.9.2 and everything is working as expected! thank you for the fix!

**Comment by gillg** [comment]
Thanks to all of you ;)
