### ISSUE TITLE
LDAP Auth Requires User

### ISSUE THREAD

**Issue by bodagetta** [gillg/OctoPrint-LDAP#9]
My LDAP server requires a username and login to authenticate before a connection can be made. How can i configure this plugin to use that type of authentication?

**Comment by gillg** [comment]
Hello !
Sorry but for now this plugin not handle case with LDAP server filterd by login/pass
In every cases, store a "master" account in octoprint could be sensitive.

I you want login to LDAP server anyway, the change should be around here : https://github.com/gillg/OctoPrint-LDAP/blob/master/octoprint_auth_ldap/__init__.py#L152

Sorry I have no time to test it but you can try and make a PR :)

**Comment by gillg** [comment]
Issue solved in #11
